#### Import thư viện numpy

In [1]:
import numpy as np

#### Import tập dữ liệu

In [2]:
dataset = np.loadtxt('ex2data1.txt', delimiter = ',')
X = dataset[:, :-1]
y = dataset[:, -1]

In [3]:
X[:5, :]

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644]])

In [4]:
y[:5]

array([0., 0., 0., 1., 1.])

#### Chia tập dữ liệu thành traning set và test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                    random_state = 0)

#### Feature Scaling

In [6]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler= StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train[:5,:]

array([[ 0.80451601, -1.39362426],
       [-0.50529573, -1.46548914],
       [-0.3082451 ,  1.02645931],
       [-0.11480873,  0.58805764],
       [-0.20592373, -0.78753542]])

In [8]:
X_test[:5, :]

array([[ 0.69524825, -1.17098365],
       [-1.21642081,  0.6311251 ],
       [-1.52879253,  0.31636331],
       [-0.83969052, -0.37714832],
       [ 1.68018881,  0.28813469]])

#### Huấn luyện mô hình trên training set

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [12]:
print('w optimal: ', classifier.coef_)

w optimal:  [[2.08761667 2.07706847]]


#### Dự đoán kết quả thông qua test set

In [13]:
y_pred = classifier.predict(X_test).reshape(-1, 1)
y_test = y_test.reshape(-1, 1)
result = np.concatenate((y_test, y_pred), 
                        axis = 1)

In [14]:
result[:10]
# Left: test values, right: predict values

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.]])

#### Tính Accuracy Score

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8

#### Confusion matrix

In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[8 0]
 [4 8]]


#### Balanced accuracy

In [17]:
from sklearn.metrics import balanced_accuracy_score
print(balanced_accuracy_score(y_test, y_pred))

0.8333333333333333


#### Precision

In [18]:
from sklearn.metrics import precision_score
print(precision_score(y_test, y_pred))

1.0


#### Recall

In [19]:
from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred))

0.6666666666666666
