#### Import the libraries

In [88]:
import numpy as np

#### Import the dataset

In [89]:
dataset = np.loadtxt('ex1data2.txt', delimiter = ',')
X = dataset[:, :-1]
y = dataset[:, -1].reshape(-1, 1)

In [90]:
X[:5, :]

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00]])

In [91]:
y[:5]

array([[399900.],
       [329900.],
       [369000.],
       [232000.],
       [539900.]])

#### Split the dataset into training set and test set

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                    random_state = 0)

In [93]:
X_train[:5,:]

array([[2526.,    3.],
       [2040.,    4.],
       [2637.,    3.],
       [1200.,    3.],
       [2400.,    3.]])

In [94]:
y_train[:5]

array([[469000.],
       [314900.],
       [299900.],
       [299000.],
       [369000.]])

In [95]:
X_test[:5, :]

array([[2.200e+03, 3.000e+00],
       [3.137e+03, 3.000e+00],
       [1.839e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [2.609e+03, 4.000e+00]])

In [96]:
y_test[:5]

array([[475000.],
       [579900.],
       [349900.],
       [539900.],
       [499998.]])

#### Feature Scaling

In [97]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
y_train = sc_y.fit_transform(y_train)

In [98]:
X_train[:5,:]

array([[ 0.70478365, -0.27372166],
       [ 0.11051283,  1.17309283],
       [ 0.84051217, -0.27372166],
       [-0.91662193, -0.27372166],
       [ 0.55071344, -0.27372166]])

In [99]:
y_train[:5]

array([[ 1.15924789],
       [-0.13370043],
       [-0.25955523],
       [-0.26710652],
       [ 0.32021588]])

In [100]:
X_test[:5, :]

array([[ 0.30615754, -0.27372166],
       [ 1.45190191, -0.27372166],
       [-0.13526585, -1.72053615],
       [ 1.28438112,  1.17309283],
       [ 0.80627435,  1.17309283]])

#### Training Linear Regression model in training set

In [101]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [104]:
print('\t\tw optimal: ', regressor.coef_)

		w optimal:  [[ 0.86356602 -0.00926087]]


#### Predict the Test set results

In [102]:
y_pred = regressor.predict(X_test)
y_pred = sc_y.inverse_transform(y_pred)
result = np.concatenate((y_test.reshape(len(y_pred), 1), y_pred.reshape(len(y_pred), 1)), 
                        axis = 1)

In [103]:
result[:10]

array([[475000.        , 362648.1885365 ],
       [579900.        , 480572.88080166],
       [349900.        , 318812.02080875],
       [539900.        , 461734.02531911],
       [499998.        , 412525.32235681],
       [347000.        , 337477.49648418],
       [314000.        , 407239.47702583],
       [169900.        , 214817.89907594],
       [242900.        , 287639.52622057],
       [239999.        , 328329.35744178]])