##Bài 1: Vector và Ma trận

Import thư viện cần thiết:

In [2]:
import numpy as np

1. Cho v là 1 vector hàng. v = [1, 2, 3, 4, 5]. Lưu ý: vector tương ứng với tensor hạng 1

In [29]:
v = np.array([1, 2, 3, 4, 5])

2. Cho w là 1 vector cột w = [1; 2; 3; 4; 5]. Lưu ý vector cũng có thể biểu diễn dưới dạng tensor hạng 2 ở trường hợp đặc biệt $R^{m \times 1}$

In [4]:
w = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

3. Hãy xác định số chiều, kích thước của 2 vector v và w; in 2 vector v và w ra màn hình; nhận xét điểm khác biệt của kết quả

* Số chiều:

In [6]:
v.ndim

1

In [7]:
w.ndim

2

* Kích thước của 2 vector:

In [8]:
v.shape

(5,)

In [9]:
w.shape

(5, 1)

* Nhận xét: v là một tensor hạng 1 hay vector (nên phép transpose không có tác dụng), w là tensor hạng 2 hay matrix

4. Cho u và w là 2 vector cột có kích thước (m, 1). Hãy tạo ma trận X bằng cách ghép 2 vector cột u và w lại với nhau X = [u, w]

In [24]:
np.random.seed(0)
u = np.random.randint(low = 0, high = 10, size = (5, 1)) # m = 5
w = np.random.randint(low = 0, high = 10, size = (5, 1))

In [25]:
u 

array([[5],
       [0],
       [3],
       [3],
       [7]])

In [26]:
w

array([[9],
       [3],
       [5],
       [2],
       [4]])

* Cách 1: Sử dụng hàm np.column_stack()

In [28]:
np.column_stack((u, w))

array([[5, 9],
       [0, 3],
       [3, 5],
       [3, 2],
       [7, 4]])

* Cách 2: Sử dụng hàm np.hstack()

In [15]:
X = np.hstack((u, v))

* Sô chiều của X:

In [17]:
X.shape 

(5, 2)

5. Hãy tạo ma trận X có giá trị như sau:
$$ X = \begin{bmatrix}
    1 & 2 & 3 & 4 & 5\\
    6 & 7 & 8 & 9 & 2\\
    4 & 5 & 7 & 2 & 1
\end{bmatrix}$$

* Tạo ma trận X bằng np array()

In [18]:
X = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 2],
    [4, 5, 7, 2, 1]
])

* Tạo ma trận X bằng hàm np.reshape()

In [20]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4, 5, 7, 2, 1]).reshape(3, -1)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 2],
       [4, 5, 7, 2, 1]])

* Xác định số chiều

In [21]:
X.ndim

2

* Xác định kích thước

In [22]:
X.shape

(3, 5)

* In nội dung ma trận X ra màn hình:

In [23]:
X

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 2],
       [4, 5, 7, 2, 1]])

6. Nhân ma trận X với vector v

In [30]:
A = np.dot(X, v)

* Xác định chiều

In [31]:
A.ndim

1

* Xác định kích thước

In [32]:
A.shape

(3,)

* In nội dung ra màn hình

In [33]:
A

array([55, 90, 48])

7. Hãy nhân ma trận X với vector w

In [35]:
B = np.dot(X, w)

* Xác định chiều, kích thước và in nội dung kết quả phép nhân ra màn hình

In [36]:
B.ndim

2

In [37]:
B.shape

(3, 1)

In [38]:
B

array([[ 58],
       [141],
       [ 94]])

* Sự khác biệt giữa câu 6 và câu 7 là sự khác biệt về hạng của 2 tensor.

8. Xét ma trận ở câu 5, hãy tìm ma trận chuyển vị của X, kí hiệu là $X^{T}$

In [41]:
X.T

array([[1, 6, 4],
       [2, 7, 5],
       [3, 8, 7],
       [4, 9, 2],
       [5, 2, 1]])