#### Import the libraries

In [1]:
import numpy as np

#### Import the dataset

In [3]:
dataset = np.loadtxt('ex2data1.txt', delimiter = ',')
X = dataset[:, :-1]
y = dataset[:, -1].reshape(-1, 1)

In [4]:
X[:5, :]

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644]])

In [5]:
y[:5]

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.]])

#### Split the dataset into training set and test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                    random_state = 0)

In [9]:
len(X_train)

80

In [10]:
len(y_train)

80

In [11]:
len(X_test)

20

In [12]:
len(y_test)

20

#### Feature Scaling

In [13]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler= StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train[:5,:]

array([[ 0.80451601, -1.39362426],
       [-0.50529573, -1.46548914],
       [-0.3082451 ,  1.02645931],
       [-0.11480873,  0.58805764],
       [-0.20592373, -0.78753542]])

In [16]:
X_test[:5, :]

array([[ 0.69524825, -1.17098365],
       [-1.21642081,  0.6311251 ],
       [-1.52879253,  0.31636331],
       [-0.83969052, -0.37714832],
       [ 1.68018881,  0.28813469]])

#### Training Linear Regression model in training set

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [18]:
print('\t\tw optimal: ', classifier.coef_)

		w optimal:  [[2.08761667 2.07706847]]


#### Predict the Test set results

In [23]:
y_pred = classifier.predict(X_test).reshape(-1, 1)
result = np.concatenate((y_test, y_pred), 
                        axis = 1)

In [24]:
result[:10]
# Left: test values, right: predict values

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.]])

#### Calculate Accuracy Score

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8