#### Import thư viện numpy:

In [1]:
import numpy as np

#### Import dataset

In [2]:
dataset = np.loadtxt('ex1data2.txt', delimiter = ',')
X = dataset[:, :-1]
y = dataset[:, -1].reshape(-1, 1)

In [3]:
X[:5, :]

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00]])

In [4]:
y[:5]

array([[399900.],
       [329900.],
       [369000.],
       [232000.],
       [539900.]])

#### Tách dataset thành training set và test set

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,
                                                    random_state = 15)

#### Feature Scaling

In [43]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

In [12]:
X_train[:5,:]

array([[ 0.2828729 ,  0.9486833 ],
       [ 0.62450945, -0.31622777],
       [-1.09802774, -0.31622777],
       [-0.52384868, -0.31622777],
       [-1.04204529, -0.31622777]])

In [13]:
y_train[:5]

array([[-0.38652346],
       [ 0.27538405],
       [-0.28965895],
       [-0.04023283],
       [-0.8474371 ]])

In [14]:
X_test[:5, :]

array([[-1.24157251, -0.31622777],
       [ 2.76332646, -0.31622777],
       [-0.78797105, -1.58113883],
       [-0.18077669, -1.58113883],
       [ 3.22984695,  0.9486833 ]])

In [45]:
y_test[:5]

array([[-0.68599625],
       [ 1.92934561],
       [-0.83048581],
       [ 0.12120803],
       [ 1.72835175]])

#### Training Linear Regression model đối với training set

In [46]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [47]:
print('\t\tw optimal: ', regressor.coef_)

		w optimal:  [[ 0.94149823 -0.08796273]]


#### Dự đoán giá trị ở test set

In [48]:
y_pred = regressor.predict(X_test)

In [53]:
y_pred[:5]

array([[-1.14112207],
       [ 2.62948324],
       [-0.60279207],
       [-0.03111965],
       [ 2.95744643]])

#### Đánh giá mô hình bằng một vài độ đo lỗi

In [51]:
from sklearn.metrics import mean_absolute_error
print(f"MAE: {mean_absolute_error(y_test, y_pred)}")

MAE: 0.5283983953889438


In [52]:
from sklearn.metrics import mean_squared_error
print(f"MSE: {mean_squared_error(y_test, y_pred)}")

MSE: 0.46209520688703887
