### BÀI ÔN TẬP KIẾN THỨC TOÁN VÀ LẬP TRÌNH

In [2]:
import numpy as np

### 1. Các phép toán với vector

* **Phép cộng 2 vector**

In [3]:
x = np.array([1, 3, 5, 7])
y = np.array([2, 4, 6, 8])
z = x + y

In [4]:
z

array([ 3,  7, 11, 15])

In [5]:
z.ndim

1

In [6]:
z.shape

(4,)

* **Phép nhân 1 đại lượng vô hướng với 1 vector**:

In [7]:
x = np.array([1, 3, 5, 7])
a = 15
z = a*x

In [8]:
z

array([ 15,  45,  75, 105])

In [9]:
z.ndim

1

In [10]:
z.shape

(4,)

* **Phép tính vô hướng của hai vector**

In [11]:
x = np.array([1, 3, 5, 7])
y = np.array([2, 4, 6, 8])
z = np.dot(x,y)

In [12]:
z

100

In [14]:
z.ndim

0

In [15]:
z.shape

()

* **Phép tích hữu hướng (cross product) 2 vector**

In [16]:
x = np.array([1,3,5])
y = np.array([2,4,6])
z = np.cross(x, y)

In [17]:
z

array([-2,  4, -2])

In [18]:
z.ndim

1

In [19]:
z.shape

(3,)

* **Phép nhân các phần tử có vị trí tương ứng (elementwise multiplication) 2 vector**

In [20]:
x = np.array([1,3,5])
y = np.array([2,4,6])
z = x*y

In [21]:
z

array([ 2, 12, 30])

In [22]:
z.ndim

1

In [23]:
z.shape

(3,)

### 2. Các phép toán với ma trận

* **Phép cộng 2 ma trận**

In [24]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
Y = np.array([1,4,5,6,7,3,4,5,6]).reshape((3,3))
Z = X + Y

In [26]:
Z

array([[ 2,  6,  8],
       [10, 12,  9],
       [11, 13, 15]])

In [27]:
Z.ndim

2

In [28]:
Z.shape

(3, 3)

* **Phép nhân ma trận với 1 đại lượng vô hướng**

In [29]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
a = 3
Z = a*X

In [30]:
Z

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [31]:
Z.ndim

2

In [32]:
Z.shape

(3, 3)

* **Phép chuyển vị ma trận (transpose)**

In [34]:
X = np.array([4,5,6,7,8,9]).reshape((2,3))
Z = X.T

In [35]:
Z

array([[4, 7],
       [5, 8],
       [6, 9]])

In [36]:
Z.ndim

2

In [37]:
Z.shape

(3, 2)

* **Phép nhân 2 ma trận**

In [38]:
X = np.array([4,5,6,7,8,9]).reshape((2,3))
Y = np.array([1,4,5,6,7,3,4,5,6]).reshape((3,3))
Z = np.dot(X, Y)

In [39]:
Z

array([[ 58,  81,  71],
       [ 91, 129, 113]])

In [40]:
Z.ndim

2

In [41]:
Z.shape

(2, 3)

* **Phép nhân các phần tử có vị trí tương đương (elementwise multiplication hay còn gọi là Hadamard product) của 2 ma trận**

In [42]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
Y = np.array([1,4,5,6,7,3,4,5,6]).reshape((3,3))
Z = X * Y

In [43]:
Z

array([[ 1,  8, 15],
       [24, 35, 18],
       [28, 40, 54]])

In [44]:
Z.ndim

2

In [45]:
Z.shape

(3, 3)

* **Tạo ma trận cột dạng đặc biệt $R^{m\times 1}$**

In [46]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((-1,1))

In [47]:
X

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
X.ndim

2

In [49]:
X.shape

(9, 1)

* **Lấy ra 1 vector hàng từ ma trận X và chuyển thành ma trận đặc biệt dạng $R^{1×n}$**

In [56]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
z = X[0, :].reshape(1, -1)

In [57]:
z

array([[1, 2, 3]])

In [58]:
z.ndim

2

In [59]:
z.shape

(1, 3)

* **Xếp thêm 1 vector cột vào đầu ma trận: $x ∈ R^m$ hay $x ∈ R^{m×1}, X ∈ R^{m×n}$**

In [60]:
X = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
z = np.ones((X.shape[0], 1))
X = np.concatenate((z, X), axis = 1)

In [61]:
X

array([[1., 1., 2., 3.],
       [1., 4., 5., 6.],
       [1., 7., 8., 9.]])

In [62]:
X.ndim

2

In [63]:
X.shape

(3, 4)

* **Tách 1 ma trận data ban đầu gồm n cột thành 1 ma trận con X chứa các n-1 cột đầu tiên và 1 vector cột y lấy ra từ cột cuối cùng của data.**

In [65]:
data = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
X = data[:, :-1]
y = data[:, -1].reshape(-1, 1)

In [66]:
X

array([[1, 2],
       [4, 5],
       [7, 8]])

In [67]:
X.ndim

2

In [68]:
X.shape

(3, 2)

In [69]:
y

array([[3],
       [6],
       [9]])

In [70]:
y.ndim

2

In [71]:
y.shape

(3, 1)

### 3. Các phép toán với tensor hạng cao ($\geq 3$)

* Tạo 1 tensor $T ∈ R^{m×n×k}$ với m = 2, n = 2 và k = 3, các giá trị
được sinh ngẫu nhiên.

In [75]:
np.random.seed(0)
m = 2
n = 2
k = 3
T = np.random.randint(low = 0, high = 10, size = m*n*k).reshape(m, n, k)

In [76]:
T

array([[[5, 0, 3],
        [3, 7, 9]],

       [[3, 5, 2],
        [4, 7, 6]]])

In [77]:
T.shape

(2, 2, 3)

* **Tạo 1 tensor $T2 ∈ R^{m×n×k×q}$ chứa 2 tensor $t1,t2 ∈ R^{n×k \times q}$, biết $t1$ và $t2$ được sinh ngẫu nhiên**

In [95]:
np.random.seed(0)
n = 2
k = 2
q = 3
t1 = np.random.randint(low = 0, high = 10, size = n*k*q).reshape(n, k, q)
t2 = np.random.randint(low = 0, high = 10, size = n*k*q).reshape(n, k, q)
T2 = np.stack((t1, t2), axis = 0)

In [96]:
T2

array([[[[5, 0, 3],
         [3, 7, 9]],

        [[3, 5, 2],
         [4, 7, 6]]],


       [[[8, 8, 1],
         [6, 7, 7]],

        [[8, 1, 5],
         [9, 8, 9]]]])

In [97]:
T2.shape

(2, 2, 2, 3)